name: Deploy to GitHub Pages

# Definiert, wann der Workflow ausgelöst werden soll
on:
  push:
    branches: 'main'  # Der Workflow wird bei jedem Push auf den 'main'-Branch ausgeführt

jobs:
  build_site:  # Job zum Erstellen der Website
    runs-on: ubuntu-latest  # Der Job wird auf der neuesten Ubuntu-Version ausgeführt
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Klont das Repository, um auf den Code zugreifen zu können

      - name: Install Node.js
        uses: actions/setup-node@v4  # Installiert Node.js
        with:
          node-version: 20  # Gibt die zu installierende Node.js-Version an
          cache: npm  # Aktiviert das Caching für npm, um die Installationszeit zu verkürzen

      - name: Install dependencies
        run: npm install  # Führt den Befehl aus, um die Abhängigkeiten aus der package.json zu installieren

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'  # Setzt die Umgebungsvariable BASE_PATH auf den Namen des Repositories
        run: |
          npm run build  # Führt den Build-Befehl aus, um die Produktionsversion der Website zu erstellen

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3  # Lädt die erstellten Artefakte hoch
        with:
          path: 'build/'  # Gibt den Pfad zu den erstellten Dateien an, die hochgeladen werden sollen

  deploy:  # Job zum Bereitstellen der Website
    needs: build_site  # Dieser Job hängt vom vorherigen Job 'build_site' ab
    runs-on: ubuntu-latest  # Der Job wird auf der neuesten Ubuntu-Version ausgeführt

    permissions:
      pages: write  # Erlaubt das Schreiben auf GitHub Pages
      id-token: write  # Erlaubt das Schreiben von ID-Token für die Authentifizierung

    environment:
      name: github-pages  # Definiert die Umgebung für die Bereitstellung
      url: ${{ steps.deployment.outputs.page_url }}  # Setzt die URL der bereitgestellten Seite

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4  # Verwendet die GitHub Action zum Bereitstellen der Website auf GitHub Pages